Validate branch name

diff --git a/.github/workflows/sdk-regression.yml b/.github/workflows/sdk-regression.yml
--- a/.github/workflows/sdk-regression.yml
+++ b/.github/workflows/sdk-regression.yml
@@ -34,6 +34,12 @@ jobs:
       - uses: xt0rted/pull-request-comment-branch@v2
         if: ${{ github.event.issue.pull_request }}
         id: comment-branch
+      - name: Validate branch name
+        run: |
+          if [[ ! "${{ steps.comment-branch.outputs.head_ref }}" =~ ^[a-zA-Z0-9_\-]+$ ]]; then
+            echo "Invalid branch name"
+            exit 1
+          fi
       - uses: actions/github-script@v4
         with:
           github-token: ${{ secrets.WORKFLOW_DISPATCH_ACTIONS_TOKEN }}
